services:
  server:
    image: ghcr.io/louismollick/kashi-koi-server:main
    restart: unless-stopped
    ports:
      - '127.0.0.1:8787:8787'
    env_file: .env
    volumes:
      - server-data:/data

volumes:
  server-data:
