#!/usr/bin/env python3
"""Extract transparent eight-frame strips and register the stationary chair.

Requires Pillow only. Originals are read-only. Run from any working directory.
"""
from collections import deque
from pathlib import Path
import json
from PIL import Image, ImageChops, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets/sprites"
FRAME_SIZE = 464


def neighbors(index, width, height):
    """Four-connected neighbors, without wrapping at row edges."""
    x, y = index % width, index // width
    if x: yield index - 1
    if x + 1 < width: yield index + 1
    if y: yield index - width
    if y + 1 < height: yield index + width


def isolate(cell, gray):
    """Flood only edge-connected gray, then discard neighboring rod fragments."""
    cell = cell.convert("RGBA")
    width, height = cell.size
    pixels = list(cell.getdata())
    background = bytearray(width * height)
    pending = deque()
    edges = list(range(width)) + list(range((height - 1) * width, height * width))
    edges += [y * width + x for y in range(height) for x in (0, width - 1)]

    def is_gray(index):
        rgb = pixels[index][:3]
        return max(rgb) - min(rgb) < 24 and max(abs(c - gray) for c in rgb) < 46

    for index in edges:
        if not background[index] and is_gray(index):
            background[index] = 1
            pending.append(index)
    while pending:
        for index in neighbors(pending.popleft(), width, height):
            if not background[index] and is_gray(index):
                background[index] = 1
                pending.append(index)

    seen = bytearray(background)
    largest = []
    for index in range(width * height):
        if seen[index]: continue
        seen[index] = 1
        pending.append(index)
        component = []
        while pending:
            point = pending.popleft()
            component.append(point)
            for adjacent in neighbors(point, width, height):
                if not seen[adjacent]:
                    seen[adjacent] = 1
                    pending.append(adjacent)
        if len(component) > len(largest): largest = component
    mask = bytearray(width * height)
    for index in largest: mask[index] = 255
    cell.putalpha(Image.frombytes("L", cell.size, bytes(mask)))
    # Transparent RGB is cleared too, so filtering cannot introduce gray halos.
    result = Image.new("RGBA", cell.size)
    result.paste(cell, (0, 0), cell.getchannel("A"))
    return result


def chair_anchor(frame):
    """Register the lower chair legs, excluding the moving head, rod and toe."""
    # The chair occupies x=55..250, y=320..430 in each original cell.
    region = frame.crop((45, 325, 250, 432))
    alpha = region.getchannel("A")
    dark = region.convert("L").point(lambda p: 255 if p < 65 else 0)
    return ImageChops.multiply(alpha, dark).filter(ImageFilter.GaussianBlur(1))


def align(frame, reference):
    """Search integer offsets against the chair/boots region of frame zero."""
    anchor = chair_anchor(frame)
    best = (float("inf"), 0, 0)
    # Blank padding prevents ImageChops.offset's wraparound entering the match.
    padded = Image.new("L", (245, 147))
    padded.paste(anchor, (20, 20))
    for dy in range(-16, 17):
        for dx in range(-16, 17):
            shifted = padded.crop((20 - dx, 20 - dy, 225 - dx, 127 - dy))
            histogram = ImageChops.difference(reference, shifted).histogram()
            error = sum(value * count for value, count in enumerate(histogram))
            candidate = (error, dx, dy)
            if candidate < best: best = candidate
    return best[1:]


def process(name, gray):
    sheet = Image.open(ROOT / f"assets/animated-{name}.png")
    frames = [isolate(sheet.crop((round(col * sheet.width / 4),
                                round(row * sheet.height / 2),
                                round((col + 1) * sheet.width / 4),
                                round((row + 1) * sheet.height / 2))), gray)
              for row in range(2) for col in range(4)]
    reference = chair_anchor(frames[0])
    offsets = [(0, 0)] + [align(frame, reference) for frame in frames[1:]]
    strip = Image.new("RGBA", (FRAME_SIZE * 8, FRAME_SIZE))
    for index, (frame, (dx, dy)) in enumerate(zip(frames, offsets)):
        strip.paste(frame, (index * FRAME_SIZE + 10 + dx, 10 + dy))
    strip.save(OUT / f"{name}.png", optimize=True)
    print(f"{name}: {FRAME_SIZE}x{FRAME_SIZE}, 8 frames, chair offsets {offsets}")
    return offsets


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    report = {name: process(name, gray) for name, gray in (("bobbing", 200), ("headbang", 187))}
    (OUT / "metadata.ts").write_text(
        "// Generated by scripts/process-sprites.py. Do not edit by hand.\n"
        f"export const spriteFrames = {{ width: {FRAME_SIZE}, height: {FRAME_SIZE}, count: 8 }} as const;\n")
    (OUT / "alignment.json").write_text(json.dumps(report, indent=2) + "\n")


if __name__ == "__main__": main()
